# Generated by Django 5.0.6 on 2024-09-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(max_length=100),
        ),
    ]
