# Generated by Django 5.0.6 on 2024-09-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blog_author_blog_updated_at_alter_blog_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="blog",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
