# Generated by Django 5.0.6 on 2024-09-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_blog_category_remove_blog_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="views",
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
        migrations.AddField(
            model_name="blog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
