# Generated by Django 5.0.6 on 2024-09-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_remove_blog_views_blog_category_blog_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
