# Generated by Django 5.0.6 on 2024-09-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
