# Generated by Django 5.0.6 on 2024-09-30 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
