"""
Django settings for blogproject project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4#96j&5t-syym3uq33=+)uvb4wk2m$i&&_bf*rv!+(9g#cv@^&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# blogproject/settings.py

# ที่เก็บไฟล์ static ของโปรเจค
STATIC_URL = '/static/'

# ถ้าคุณใช้โฟลเดอร์ static ในโครงการหลัก
STATICFILES_DIRS = [
    BASE_DIR / "static",  # ระบุว่าไฟล์ static จะอยู่ในโฟลเดอร์ static ของโปรเจค
]

# สำหรับ production ใช้เมื่อ collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"




TAILWIND_APP_NAME = 'theme'  # ชื่อแอปที่ถูกสร้างโดย Tailwind

NPM_BIN_PATH = r'C:\Program Files\nodejs\npm.cmd'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # ตัวจัดการการพิสูจน์ตัวตนมาตรฐานของ Django
]


import os  # เพิ่มบรรทัดนี้ที่ด้านบนของไฟล์ settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = 'login'  # เปลี่ยนไปยังเส้นทางของหน้า login
LOGIN_REDIRECT_URL = 'home'  # หน้าแรกหลังจากที่ล็อกอินเสร็จ
LOGOUT_REDIRECT_URL = '/'  # เปลี่ยนไปยังหน้าที่คุณต้องการ



# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'forgetd69@gmail.com'  # เปลี่ยนเป็นอีเมลของคุณ
EMAIL_HOST_PASSWORD = 'mislcvhkaltirjsr'     # รหัสผ่านอีเมลของคุณ
DEFAULT_FROM_EMAIL = 'forgetd69@gmail.com'






INSTALLED_APPS = [
    'blog',
    'theme',
    'tailwind',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # ตรวจสอบว่ามี middleware นี้
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = "blogproject.urls"

# blogproject/settings.py
import os  # เพิ่มบรรทัดนี้ที่ด้านบนของไฟล์ settings.py

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # ใช้ os.path.join() แทน
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]







WSGI_APPLICATION = "blogproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
